### ISSUE TITLE
Missing definition files

### ISSUE THREAD

**Issue by abinici** [nestjsx/automapper#121]
Hi,

I was looking for a mapper library for my NestJS project and found this project.

But I ran into an issue during setup. When I added the module to my main module, VS Code was not able to auto import this module.

Then I looked in node_modules/nestjs-automapper and saw that there were only js files:

![image](https://user-images.githubusercontent.com/4557771/77683143-46b1f000-6f98-11ea-8082-f613db76f2a8.png)

The typescript definition files seems to be missing.

**Comment by gpa** [comment]
I also just was looking at this library and ran into this issue.
By downgrading to 2.0.30 I could get the types back but I couldn't bring the .map method to work. It throws even though my types are correct and mappings in the injected mapper instance registered. An example nestjs project would be really useful.

**Comment by nartc** [comment]
Thanks for reporting. I'll take a look asap :)

**Comment by abinici** [comment]
I actually ended up adding the previous project as a module in my NestJS project:

`https://github.com/nartc/nest-automapper`

Because I needed the `forFeature` method of registering the module:

`AutomapperModule.forFeature({name: 'common', profiles: [CountryProfile]})`

`forFeature` is missing in current project.

**Comment by abinici** [comment]
I actually ended up adding the previous project as a module in my NestJS project:

`https://github.com/nartc/nest-automapper`

When this issue gets fixed, then I can move back to this project.

**Comment by nartc** [comment]
@abinici That library uses an old automapper (deprecated) of mine. Please use the `nestjsx-automapper` one. I just pushed a release. I'll test on an example app then will get back to you

**Comment by nartc** [comment]
@abinici  @gpa 
![image](https://user-images.githubusercontent.com/25516557/77758116-6846c200-7000-11ea-9ffb-05e43b4aa921.png) 
definitions should be there again :) Sorry for the inconvenience.

**Comment by abinici** [comment]
Thank you @nartc for the quick response and help, I will give it a try  :)
