### ISSUE TITLE
Please provide some basicly and completely demos

### ISSUE THREAD

**Issue by santa955** [nestjsx/automapper#131]
Thanks for you provided a so excellent ts mapper.
But when I integrate the mapper into my project, I encounter some problem. Could you provide some basicly and completely demos?

**Comment by nartc** [comment]
Thanks for the kind words. What kind of example are you looking for?

**Comment by nartc** [comment]
https://codesandbox.io/s/automapper-demo-latest-ggx3f?file=/src/index.ts here's a sample usage on codesandbox for the core `@nartc/automapper`. If you're looking for specific use-case with NestJS, please elaborate :)

**Comment by santa955** [comment]
Thanks for your reply. 
I had read the sample on https://codesandbox.io/s/automapper-demo-latest-ggx3f?file=/src/index.ts .
I also read the document and find a good example in test folder that how to use the mapper in nestjs. 
But If you can provide a completely demo  to use it in Nestjs maybe a wonderful work.

**Comment by nartc** [comment]
@yandan66 I'm working on a NestJS tutorial. It is still a WIP but maybe it can provide you some guidance, I hope. Check it out at this repo: https://github.com/nartc/task-tracker/tree/master/server 

I'm going to close the issue. Feel free to open a new issue if you have other questions.
