### ISSUE TITLE
Could you please take a look at my stackoverflow question?

### ISSUE THREAD

**Issue by thijmau** [nestjsx/automapper#256]
I followed the exact documentation, but it's still not working after trying numerous things.

https://stackoverflow.com/questions/63470364/nestjs-and-nestjsxautomapper-resulting-in-error-cannot-read-property-plugin-of

Thanks in advance!

**Comment by nartc** [comment]
Answered. For the Mongoose question, please visit https://discord.gg/sszmzqn for further support. Thanks!
