### ISSUE TITLE
Fix `@nestjs/common` peerDependency version

### ISSUE THREAD

**Issue by micalevisk** [nestjsx/automapper#292]
https://github.com/nestjsx/automapper/blob/7fa616d4cf8d6e281adc26a3e299053406bfb8ab/package.json#L123-L124
I think this should be **`>=7.4.4`** since the newest release version of `@nestjs/common` is **v7.4.4**

This change was made in 0e9e9b50efdd790890301aea5b5a16ac6e52dace

**Comment by nartc** [comment]
Thanks for reporting. I'll make the change ASAP. Not sure why renovate-bot removes `=` everytime nestjs monorepo updates.

EDIT: this is part of NestJSX org so I don't have renovate-bot setup. dependabot is kinda meh!
