### ISSUE TITLE
How could I map array properties between classes?

### ISSUE THREAD

**Issue by anrolmar** [nestjsx/automapper#300]
Hi. I have class with an array property:

```
export class DocumentDto {
    @AutoMap()
    name: string;

    @AutoMap(() => UsbDto)
    usbs: UsbDto[];
}
```

and I want to map it to the next class:

```
export class DocumentModel {
    @AutoMap()
    name: string;

    @AutoMap(() => UsbModel)
    usbs: UsbModel[];
}
```

How could I map the usbs property?

Thanks.

**Comment by nartc** [comment]
Hi @anrolmar,

You would map it normally. Just ensure that a Mapping between `UsbDto` and `UsbModel` (depends on the direction `UsbDto -> UsbModel` vs `UsbModel -> UsbDto`) is available at the time of mapping by running `createMap(UserModel, UserDto).reverseMap()`

 However, there are cases that when you retrieve data, the data isn't real **instance of DocumentModel** (or vice versa). You can use `mapWith()` to ensure the mapping for nested objects/arrays will always be mapped properly:

```ts
createMap(DocumentModel, DocumentDto)
   .forMember(d => d.usbs, mapWith(UsbDto, s => s.usbs, () => UsbModel))
```

**Comment by anrolmar** [comment]
Thanks, it works with `mapWith`.
